//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLNV.Helper.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da Ton Tai.
        /// </summary>
        internal static string DaTonTai {
            get {
                return ResourceManager.GetString("DaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap khong hop le, kiem tra lai!.
        /// </summary>
        internal static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap dia chi:.
        /// </summary>
        internal static string inDiaChi {
            get {
                return ResourceManager.GetString("inDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ID du an:.
        /// </summary>
        internal static string inDuAnID {
            get {
                return ResourceManager.GetString("inDuAnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Email:.
        /// </summary>
        internal static string inEmail {
            get {
                return ResourceManager.GetString("inEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ghi chu:.
        /// </summary>
        internal static string inGhiChu {
            get {
                return ResourceManager.GetString("inGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ho ten:.
        /// </summary>
        internal static string inHoten {
            get {
                return ResourceManager.GetString("inHoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap he so luong:.
        /// </summary>
        internal static string inHSLuong {
            get {
                return ResourceManager.GetString("inHSLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap mo ta:.
        /// </summary>
        internal static string inMota {
            get {
                return ResourceManager.GetString("inMota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay sinh:.
        /// </summary>
        internal static string inNgaySinh {
            get {
                return ResourceManager.GetString("inNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap nhan vien ID:.
        /// </summary>
        internal static string inNhanVienID {
            get {
                return ResourceManager.GetString("inNhanVienID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so dien thoai:.
        /// </summary>
        internal static string inSDT {
            get {
                return ResourceManager.GetString("inSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so gio lam:.
        /// </summary>
        internal static string inSoGioLam {
            get {
                return ResourceManager.GetString("inSoGioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten du an:.
        /// </summary>
        internal static string inTenDuAn {
            get {
                return ResourceManager.GetString("inTenDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong Ton Tai.
        /// </summary>
        internal static string KhongTonTai {
            get {
                return ResourceManager.GetString("KhongTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuc hien thanh cong!.
        /// </summary>
        internal static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
    }
}
