// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNV.Entities;

#nullable disable

namespace QLNV.Migrations
{
    [DbContext(typeof(AppDbConText))]
    [Migration("20230704164555_update_v.1")]
    partial class update_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNV.Entities.DuAn", b =>
                {
                    b.Property<int>("DuAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuAnID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DuAnID");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("QLNV.Entities.NhanVien", b =>
                {
                    b.Property<int>("NhanVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanVienID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QLNV.Entities.PhanCong", b =>
                {
                    b.Property<int>("PhanCongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanCongID"));

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("SoGioLam")
                        .HasColumnType("int");

                    b.HasKey("PhanCongID");

                    b.HasIndex("DuAnID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("QLNV.Entities.PhanCong", b =>
                {
                    b.HasOne("QLNV.Entities.DuAn", "DuAn")
                        .WithMany("PhanCong")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNV.Entities.NhanVien", "NhanVien")
                        .WithMany("PhanCong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNV.Entities.DuAn", b =>
                {
                    b.Navigation("PhanCong");
                });

            modelBuilder.Entity("QLNV.Entities.NhanVien", b =>
                {
                    b.Navigation("PhanCong");
                });
#pragma warning restore 612, 618
        }
    }
}
